case_name: latency_compensated_replay
description: "A demo case for replaying latent vehicle data with prediction and visualization."

# ==============================================================================
# I/O Mapping
# ------------------------------------------------------------------------------
# This section maps logical I/O names used by plugins to physical file paths.
# This allows the same plugin to be reused across different cases by simply
# re-wiring its inputs and outputs here.
# ==============================================================================
io_mapping:
  # --- For LatencyCompensator ---
  latent_measurements:
    path: "raw_data/latent_measurements.csv"
    handler: "csv"
  predicted_states:
    path: "intermediate/predicted_states.parquet"
    handler: "parquet"

  # --- For FrameRenderer ---
  video_manifest:
    path: "raw_data/video_manifest.csv"
    handler: "csv"
  # FrameRenderer's output is the input for VideoCreator
  rendered_frames:
    path: "intermediate/rendered_frames"
    handler: "dir" # Assuming a 'dir' handler that provides the path

  # --- For VideoCreator ---
  replay_video:
    path: "output/replay_video.mp4"
    # The handler can be inferred from the extension, or specified explicitly.
    # For video, a special handler would be needed if we were to 'load' it,
    # but for saving, the plugin handles it directly. The framework just
    # needs the path.

# ==============================================================================
# Pipeline Configuration
# ------------------------------------------------------------------------------
# The `config` section for each plugin now only contains pure algorithm
# parameters. All I/O declarations are gone from here and live in the code
# as `DataSource`/`DataSink` annotations, wired up by `io_mapping`.
# ==============================================================================
pipeline:
  # ------------------------------------------------------------------------------
  # Plugin 2: LatencyCompensator
  # ------------------------------------------------------------------------------
  - plugin: "Latency Compensator"
    enable: true
    config:
      latency_to_compensate_s: 0.2

  # ------------------------------------------------------------------------------
  # Plugin 3: FrameRenderer
  # ------------------------------------------------------------------------------
  - plugin: "Frame Renderer"
    enable: true
    config:
      zoom_factor: 5

  # ------------------------------------------------------------------------------
  # Plugin 4: VideoCreator
  # ------------------------------------------------------------------------------
  - plugin: "Video Creator"
    enable: true
    config:
      fps: 50